### Get all pets

GET http://localhost:8080/pets

### Get 1 Pet

GET http://localhost:8080/pets/67a7886daffa2e1caba0d3e2

### Create a Pet
POST http://localhost:8080/pets 
content-type: application/json

{
    "name": "Fluffy",
    "species": "Dog",
    "breed": "Cerberus",
    "age": 3000,
    "adoption_status": false,
    "description": "A playful and energetic dog who loves fetch.",
    "image_url": "https://example.com/fluffy.jpg",
}

### Delete a Pet

DELETE http://localhost:8080/pets/67a7855a8b7f3bc85caa5fe3

### Get All Users

GET http://localhost:8080/users

### Get 1 User

GET http://localhost:8080/users/67a78ae72ce6151aaa3d62c6

### Create a User

POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "github_id": "12345",
  "profile_url": "https://github.com/johndoe",
  "avatar_url": "https://example.com/avatar.jpg",
  "password": "securePassword123"
}