### Get all pets

GET http://localhost:8080/pets

### Get 1 Pet

GET http://localhost:8080/pets/67a7886daffa2e1caba0d3e2

### Create a Pet
POST http://localhost:8080/pets 
content-type: application/json

{
    "name": "Fluffy",
    "species": "Dog",
    "breed": "Cerberus",
    "age": 3000,
    "adoption_status": false,
    "description": "A playful and energetic dog who loves fetch.",
    "image_url": "https://example.com/fluffy.jpg",
    "created_at": "2025-01-15T10:30:00Z"
}

### Delete a Pet

DELETE http://localhost:8080/pets/67a7855a8b7f3bc85caa5fe3

### Get All Users

GET http://localhost:8080/users

### Get 1 User

GET http://localhost:8080/users/67a6a54d497bfe3e0a2bbba0

### Create a User

POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{
    "username": "TestUser",
    "email": "testuser@test.com",
    "github_id": "testUser",
    "profile_url": "https://github.com/tech-guru87",
    "avatar_url": "https://avatars.githubusercontent.com/u/101",
    "password": "longpassword",
    "created_at": "2025-02-07T12:00:00Z",
}